first use case: integrate FrejaEid and JMeter
S-Ptr/frejaeid-jmeter-plugin-repo pull request #4
Opened 2020-03-15 13:33 UTC by risticivan12

update version

2020-03-16 11:01 UTC, aleksandarmarkovic-verisec requested changes

2020-03-16 11:01 UTC, aleksandarmarkovic-verisec commented on src/main/java/com/internship/frejaeidjmeterplugin/jmeter/frejaRequests/AuthenticationService.java
> +    public static AuthenticationService create (String keyPath, String keyPassword, String serviceAdr) throws FrejaEidClientInternalException{
We don't need two constructors for now, so my suggestion is to delete this one, define keyPath, keyPassword and serviceAddr as constants inside this class, and then to reuse them directly in authenticationClient initialization in constructor above.

2020-03-16 11:01 UTC, aleksandarmarkovic-verisec commented on src/main/java/com/internship/frejaeidjmeterplugin/jmeter/frejaRequests/AuthenticationService.java
> +    private AuthenticationService() throws FrejaEidClientInternalException {
This constructor should be public.

2020-03-16 11:01 UTC, aleksandarmarkovic-verisec commented on src/main/java/com/internship/frejaeidjmeterplugin/jmeter/frejaRequests/AuthenticationService.java
> +    private static String keystorePath;
Keystore path, keystore pass and service address should be public static final constants and properly named for that purpose - google how constants name convention in JAVA. Maybe this will change later on when we add more code.

2020-03-16 11:01 UTC, aleksandarmarkovic-verisec commented on src/main/java/com/internship/frejaeidjmeterplugin/jmeter/frejaRequests/AuthenticationService.java
> +    public static String getKeystorePassword() {
We don't need this getters

2020-03-16 11:01 UTC, aleksandarmarkovic-verisec commented on src/main/java/com/internship/frejaeidjmeterplugin/jmeter/frejaRequests/AuthenticationService.java
> +    public void sendRequest(String email, MinRegistrationLevel registrationLevel) throws FrejaEidClientInternalException, FrejaEidException, FrejaEidClientPollingException {
Rename this method to initiateAuthenticationRequest. My suggestion is also to change type from void to String and to return transaction reference.

2020-03-16 11:01 UTC, aleksandarmarkovic-verisec commented on src/main/java/com/internship/frejaeidjmeterplugin/jmeter/frejaRequests/AuthenticationService.java
> +    public AuthenticationResult getResults() throws FrejaEidClientInternalException, FrejaEidException, FrejaEidClientPollingException {
This method can accept transactionReference as argument and poll for results based on this reference.

2020-03-16 11:01 UTC, aleksandarmarkovic-verisec commented on src/main/java/com/internship/frejaeidjmeterplugin/jmeter/frejaRequests/AuthenticationService.java
> +    private InitiateAuthenticationRequest request;
This can be local method variable, so we can remove it from here.

2020-03-16 11:01 UTC, aleksandarmarkovic-verisec commented on src/main/java/com/internship/frejaeidjmeterplugin/jmeter/frejaRequests/AuthenticationService.java
> +    private String reference;
This can be method argument, so we can remove it from here.

2020-03-16 11:01 UTC, aleksandarmarkovic-verisec commented on src/main/java/com/internship/frejaeidjmeterplugin/jmeter/gui/AuthSamplerGui.form
You explained to me that initAuthentication button doesn't have much sense in JMeter, so now when we tried our test case, my suggestion is to delete it and leave empty GUI section which will be called Authentication service, for now. I will define in our next iteration what can be added here in order to try some GUI data interaction from JMete.

2020-03-16 11:01 UTC, aleksandarmarkovic-verisec commented on src/main/java/com/internship/frejaeidjmeterplugin/jmeter/gui/AuthSamplerGui.java
>  public class AuthSamplerGui extends AbstractSamplerGui {
Remove logic for button - see comment in AuthSamplerGui.form.

2020-03-16 11:01 UTC, aleksandarmarkovic-verisec commented on src/main/java/com/internship/frejaeidjmeterplugin/jmeter/gui/AuthSamplerGui.java
>      // Variables declaration - do not modify//GEN-BEGIN:variables
Move variables declaration at the beginning of the class.

2020-03-16 11:01 UTC, aleksandarmarkovic-verisec commented on src/main/java/com/internship/frejaeidjmeterplugin/jmeter/gui/AuthSamplerGui.java
Move creatingParallelGroup and creatingVerticalGroup into separate private methods which will describe what this pieces of code do and reuse them here. I think this way it will be much more readable because this method already has too many lines of code.

2020-03-16 11:01 UTC, aleksandarmarkovic-verisec commented on src/main/java/com/internship/frejaeidjmeterplugin/jmeter/gui/AuthSamplerGui.form
You explained to me that button for sending authentication doesn't make much sense in JMeter, and we already used it for our test case, so for now, we can remove it and leave this GUI section with label Authentication service.

2020-03-16 11:01 UTC, aleksandarmarkovic-verisec commented on src/main/java/com/internship/frejaeidjmeterplugin/jmeter/gui/AuthSamplerGui.java
>      // Variables declaration - do not modify//GEN-BEGIN:variables
Move variables at beginning of the class.

2020-03-16 11:01 UTC, aleksandarmarkovic-verisec commented on src/main/java/com/internship/frejaeidjmeterplugin/jmeter/gui/AuthSamplerGui.java
>      private void initComponents() {
Consider refactoring this method into few private methods because it already has too many lines of code. 
My suggestion is to move setting paralel and vertical groups to two separate private methods, describe what this methods do and then reuse them here. It will be more readable.

2020-03-17 10:14 UTC, S-Ptr approved these changes

2020-03-17 10:25 UTC, aleksandarmarkovic-verisec commented on src/main/java/com/internship/frejaeidjmeterplugin/jmeter/sample/AuthSample.java
> +    private AuthenticationService initRequest;
rename this to authService

2020-03-17 10:25 UTC, aleksandarmarkovic-verisec commented on src/main/java/com/internship/frejaeidjmeterplugin/jmeter/sample/AuthSample.java
> +        initRequest = new AuthenticationService();
move initialization of AuthenticationService in constructor

2020-03-17 10:25 UTC, aleksandarmarkovic-verisec commented on src/main/java/com/internship/frejaeidjmeterplugin/jmeter/sample/AuthSample.java
> +    public String sendInitAuthenticate(String email, MinRegistrationLevel registrationLevel) throws FrejaEidClientInternalException, FrejaEidException, FrejaEidClientPollingException {
I don't think this method is necesseary, we can directly call authService.initAuthRequest

2020-03-17 10:25 UTC, aleksandarmarkovic-verisec commented on src/main/java/com/internship/frejaeidjmeterplugin/jmeter/sample/AuthSample.java
> +    public AuthenticationResult getResultsInitAuthenticate(String reference) throws FrejaEidException, FrejaEidClientPollingException, FrejaEidClientInternalException {
I don't think we need this method, samd comment as for initAuth.

2020-03-17 10:45 UTC, aleksandarmarkovic-verisec approved these changes

2020-03-17 11:23 UTC, merged